# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f14d2898dc45990192f7d6e8c170e03774ff5f9cea398d4719db9d6b45b3efbe0fb431df85391e526bcf2486540e924561a840297270a7e0584bcacaded0ebb8

test:
  secret_key_base: 93f1c64920e7d8f90bc7f2de681eeef6c5a9c489d90f44e82fe4cfe4ddbfbca218198fe57173f30b133449c94cf8e0bc5d204864ce800e3d472d5dca7e0b2db9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
